#!/usr/bin/env bash
# DynamicCodec — 8 component combinations (run reference + inline configs).
#
# Usage:
#   bash bash.sh                 # list combos
#   bash bash.sh <combo>         # run smoke inference for a single combo
#   bash bash.sh all             # run all 8 sequentially
#   bash bash.sh train <combo>   # run training for a single combo (needs VCTK manifest)
#
# Combos:
#                  input    encoder    quantizer  decoder    vocoder   ckpt
#   1) dac-rvq         wav    dac        rvq        dac        -        runs/dac-result/best (pretrained, 48 kHz, 8 codebooks)
#   2) dac-vq          wav    dac        vq         dac        -        random init
#   3) dac-bsq         wav    dac        bsq        dac        -        random init
#   4) dac-fsq         wav    dac        fsq        dac        -        random init  (FSQ, levels=[8,5,5,5] → 1000 codes)
#   5) encodec-rvq     wav    encodec    rvq        encodec    -        random init
#   6) mel-rvq         mel    mel        rvq        mel        -        random init  (mel-domain reconstruction, no vocoder)
#   7) mel-rvq-vocos   mel    mel        rvq        mel        vocos    random init  (mel → vocoder → wav)
#   8) repcodec-rvq    repr   repcodec   rvq        dac        -        needs ckpt/data2vec/base_no_ft.pt for SSL features
#
# 自定义环境（按需修改顶上几行）：HF_HOME / conda env path / DynamicCodec 仓库路径。
# 实际跑模型走的是 dyc_dev / dyc_luki 容器里的 python，不依赖宿主机 conda 环境。

# ----- host-side env (optional, only if you also want to run python on host) -----
export HF_HOME=/path/to/huggingface
# source /path/to/anaconda3/bin/activate /path/to/anaconda3/envs/dynamic
cd "$(dirname "$0")"
export PYTHONPATH="$PWD:$PYTHONPATH"

# ----- container detection -----
# Prefer dyc_dev (renamed); fall back to dyc_luki for back-compat.
pick_container() {
    if sudo docker ps --format '{{.Names}}' 2>/dev/null | grep -qx dyc_dev; then
        echo dyc_dev
    elif sudo docker ps --format '{{.Names}}' 2>/dev/null | grep -qx dyc_luki; then
        echo dyc_luki
    else
        echo ""
    fi
}

DYC_CTR="$(pick_container)"
if [ -z "$DYC_CTR" ]; then
    echo "no DynamicCodec container running. start one with: bash scripts/setup_container.sh" >&2
    exit 1
fi

# Combo conf files live under conf/combos/. We (re)write them on every run so
# the file embedded below is always the source of truth — feel free to edit
# them in place if you want different hyperparameters per combo.
CONF_DIR=conf/combos
mkdir -p "$CONF_DIR"

# ----- combo conf renderer -----------------------------------------------------
# write_conf <combo_id> <input_format> <encoder> <quantizer> <decoder> <vocoder|null> <resume:true|false>
# Skips if the file already exists, so edits to conf/combos/*.yaml persist
# across runs. Delete the file to regenerate from scratch.
write_conf() {
    local id=$1 ifmt=$2 enc=$3 qnt=$4 dec=$5 voc=$6 resume=$7
    local f="$CONF_DIR/${id}.yaml"
    if [ -f "$f" ]; then
        echo "$f"
        return
    fi
    {
        echo "# Auto-generated by bash.sh; safe to edit if you want combo-specific tweaks."
        echo "# bash.sh will not overwrite this file once it exists; delete to regenerate."
        echo '$include:'
        echo "  - ../input/${ifmt}.yaml"
        echo "  - ../model/encoder/${enc}.yaml"
        echo "  - ../model/decoder/${dec}.yaml"
        echo "  - ../model/quantizer/${qnt}.yaml"
        [ "$voc" != "null" ] && echo "  - ../model/vocoder/${voc}.yaml"
        echo
        echo "# component identity (consumed by model/build.py:build_model)"
        echo "input_format: ${ifmt}"
        echo "encoder: ${enc}"
        echo "quantizer: ${qnt}"
        echo "decoder: ${dec}"
        echo "vocoder: ${voc}"
        echo
        echo "# inference runtime"
        echo "sample_rate: 48000"
        echo "batch_size: 1"
        echo "device: cuda:0"
        echo "ssl_model.device: cuda:0"
        echo "seed: 42"
        echo "resume: ${resume}"
        if [ "$resume" = "true" ]; then
            echo "exp_name: dac-result   # checkpoint dir name (relative to runs/)"
            echo "tag: best              # which subdir of exp_name to load"
        fi
    } > "$f"
    echo "$f"
}

# Render all 8 combo confs (idempotent).
render_all_confs() {
    write_conf dac_rvq        wav     dac      rvq  dac      null   true   >/dev/null
    write_conf dac_vq         wav     dac      vq   dac      null   false  >/dev/null
    write_conf dac_bsq        wav     dac      bsq  dac      null   false  >/dev/null
    write_conf dac_fsq        wav     dac      fsq  dac      null   false  >/dev/null
    write_conf encodec_rvq    wav     encodec  rvq  encodec  null   false  >/dev/null
    write_conf mel_rvq        melspec mel      rvq  mel      null   false  >/dev/null
    write_conf mel_rvq_vocos  melspec mel      rvq  mel      vocos  false  >/dev/null
    write_conf repcodec_rvq   repr    repcodec rvq  dac      null   false  >/dev/null
}

# ----- runners ----------------------------------------------------------------
run_infer() {
    local id=$1
    render_all_confs
    local conf="$CONF_DIR/${id}.yaml"
    [ -f "$conf" ] || { echo "unknown combo: $id (see 'bash bash.sh' for the list)" >&2; exit 2; }
    local save="runs/combo_${id}"
    echo "==> [infer] $id"
    echo "    conf: $conf   save: $save"
    sudo docker exec "$DYC_CTR" bash -c \
        "cd /app && PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python main.py \
            --conf_path $conf --save_path $save --args.debug 1"
}

run_train() {
    local id=$1
    render_all_confs
    local conf="$CONF_DIR/${id}.yaml"
    [ -f "$conf" ] || { echo "unknown combo: $id" >&2; exit 2; }
    local save="runs/train_${id}"
    echo "==> [train] $id"
    echo "    conf: $conf   save: $save"
    echo "    note: needs VCTK manifest (data/manifests/vctk/*.csv) — build with"
    echo "          scripts/build_vctk_manifest.py before training."
    # Training also needs the train.yaml inclusion for hyperparams. Easiest path:
    # base.yaml's state-driven include picks up conf/train.yaml when state=train.
    # We point train.py at base.yaml and override the 5 component fields via the
    # combo conf merged on top.
    sudo docker exec "$DYC_CTR" bash -c \
        "cd /app && PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python train.py \
            --conf_path $conf --save_path $save --args.debug 1"
}

run_all_infer() {
    for id in dac_rvq dac_vq dac_bsq dac_fsq encodec_rvq mel_rvq mel_rvq_vocos repcodec_rvq; do
        run_infer "$id" || echo "  FAILED: $id"
        echo
    done
}

usage() {
    sed -n '1,28p' "$0"
}

# ----- dispatcher -------------------------------------------------------------
case "${1:-}" in
    "")        usage ;;
    -h|--help) usage ;;
    all)       run_all_infer ;;
    train)
        [ -n "${2:-}" ] || { echo "train needs a combo id" >&2; exit 2; }
        run_train "${2//-/_}"
        ;;
    *)
        # accept either dash- or underscore-separated combo ids
        run_infer "${1//-/_}"
        ;;
esac
