$include:
  - conf/&{state}.yaml
  - conf/input_format/&{input_format}.yaml
  - conf/model/encoder/&{encoder}.yaml
  - conf/model/decoder/&{decoder}.yaml
  - conf/model/quantizer/&{quantizer}.yaml




# model component
state: train # train/inference
input_format: repr # repr/wav/melspec
encoder: encodec
decoder: dac
quantizer: rvq


# resume: true  # path to checkpoint to resume training from
# exp_name: encodec+dac
# tag: best


