$include:
  - conf/&{state}.yaml
  - conf/input_format/&{input_format}.yaml
  - conf/model/encoder/&{encoder}.yaml
  - conf/model/decoder/&{decoder}.yaml
  - conf/model/quantizer/&{quantizer}.yaml
  - conf/model/vocoder/&{vocoder}.yaml




# model component
state: inference # train/inference
input_format: repr # repr/wav/melspec
encoder: repcodec
quantizer: rvq
decoder: mel
vocoder: vocos
# vocoder: null
