$include:
  - conf/&{state}.yaml
  - conf/input_format/&{input_format}.yaml
  - conf/model/encoder/&{encoder}.yaml
  - conf/model/decoder/&{decoder}.yaml
  - conf/model/quantizer/&{quantizer}.yaml
  - conf/model/vocoder/&{vocoder}.yaml




# model component
state: inference # train/inference
input_format: melspec # repr/wav/melspec
encoder: mel
quantizer: rvq
decoder: mel
output_format: melspec  # wav/melspec
vocoder: vocos
