$include:
  - conf/&{state}.yaml
  - conf/input_format/&{input_format}.yaml
  - conf/model/encoder/&{encoder}.yaml
  - conf/model/decoder/&{decoder}.yaml
  - conf/model/quantizer/&{quantizer}.yaml




# model component
state: inference # train/inference
input_format: wav # repr/wav/melspec
encoder: dac
decoder: dac
quantizer: rvq